language: python
python:
  - 2.7
  - 3.4
  - pypy
env:
  - DJANGO=1.9.12
  - DJANGO=1.10.4
install:
  - pip install -e .
  - pip install -q Django==$DJANGO
script:
  - DJANGO_SETTINGS_MODULE=suit.tests.settings django-admin test suit
